name: Deploy Next.js to Vercel

on:
  push:
    branches:
      - master # Trigger on pushes to the main branch
  pull_request:
    branches:
      - master # Trigger on pull requests targeting the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Action to check out your repository code

      - name: Setup Node.js environment
        uses: actions/setup-node@v4 # Action to set up Node.js
        with:
          node-version: '20' # Specify your Node.js version
          cache: 'npm' # Cache npm dependencies for faster builds

      - name: Install dependencies
        run: npm ci # Install project dependencies (use 'npm ci' for clean install)

      - name: Run ESLint (optional, but recommended)
        run: npm run lint # Assuming you have a "lint" script in package.json

      - name: Build Next.js project
        run: npm run build # Build your Next.js application

      - name: Deploy to Vercel
        uses: vercel/actions/deploy@v2 # Official Vercel GitHub Action for deployment
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          org-id: ${{ secrets.VERCEL_ORG_ID }}
          project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          root-directory: ./multi-channel-chat-app
          production: true